codecov:
    require_ci_to_pass: false

coverage:
    precision: 2
    round: down
    status:
        project:
            default:
                target: 90%
                informational: true
        patch: false
        changes: false

comment: false

ignore:
    - "xmitgcm/test/*"
    - "xmitgcm/__init__.py"
    - "setup.py"
    - "xmitgcm/llcreader/*"
