codecov:
  config: codecov.yml
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 90%
        informational: true
  ignore:
    - "xmitgcm/test/test_llcreader.py"
    - "xmitgcm/__init__.py"
    - "setup.py"
    - "xmitgcm/llcreader/*"

comment: false
