name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - zarr
  - cftime
  - aiohttp
  - pytest-cov
  - codecov
  - fsspec
  - cachetools
